import "./globals.css";
import Header from "./components/Header";

export const metadata = {
  title: "myblog",
  description: "Generated by create next app",
  keywords: ["my next site, next js,react,javascript,node"],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="title" content="myblog" />
      {/* Open Graph / Facebook */}
      <meta property="og:type" content="website" />
      <meta property="og:url" content="https://metatags.io/" />
      <meta property="og:title" content="myblog" />
      <meta property="og:description" content="my next site, next js,react,javascript,node" />
      <meta property="og:image" content="/favicon.ico" />
      <meta property="twitter:card" content="summary_large_image" />
      <meta property="twitter:url" content="https://metatags.io/" />
      <meta property="twitter:title" content="myblog" />
      <meta property="twitter:description" content="my next site, next js,react,javascript,node" />
      <meta property="twitter:image" content="https://metatags.io/images/meta-tags.png" />
      <meta name="robots" content="all" />
      <body>
        <Header />
        <main className="container mx-auto px-5 mt-20 md:mt-0">{children}</main>
      </body>
    </html>
  );
}
